
-- TABLAS
CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" VARCHAR(50) UNIQUE NOT NULL,
  "descripcion" VARCHAR(255),
  "activo" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "usuarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol_id" BIGINT NOT NULL,
  "nombre" VARCHAR(80) NOT NULL,
  "apellido_paterno" VARCHAR(80) NOT NULL,
  "apellido_materno" VARCHAR(80),
  "nacimiento" DATE NOT NULL,
  "genero" VARCHAR(15) CHECK (genero IN ('masculino', 'femenino', 'otro')),
  "foto_url" VARCHAR(500),
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'inactivo', 'bloqueado')) DEFAULT 'activo',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_cuenta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "username" VARCHAR(100) UNIQUE NOT NULL,
  "email" VARCHAR(150) UNIQUE,
  "password_hash" VARCHAR(255) NOT NULL,
  "email_verificado" BOOLEAN NOT NULL DEFAULT false,
  "ultimo_login" TIMESTAMPTZ,
  "intentos_fallidos" SMALLINT NOT NULL DEFAULT 0,
  "bloqueado_hasta" TIMESTAMPTZ,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_documentos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "tipo_doc" VARCHAR(30) NOT NULL,
  "numero_doc" VARCHAR(50) UNIQUE NOT NULL,
  "doc_url" VARCHAR(500),
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_direcciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "zona" VARCHAR(90) NOT NULL,
  "distrito" VARCHAR(100),
  "bloque" VARCHAR(100),
  "calle" VARCHAR(100),
  "numero" VARCHAR(50),
  "edificio" VARCHAR(100),
  "piso" INT,
  "referencia" TEXT,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_contactos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "tipo" VARCHAR(30) NOT NULL,
  "contenido" VARCHAR(200) NOT NULL,
  "principal" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "estudiantes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "fecha_ingreso" DATE NOT NULL,
  "fecha_egreso" DATE,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'retirado', 'egresado', 'suspendido')) DEFAULT 'activo',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "apoderados" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "ocupacion" VARCHAR(100),
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "estudiante_apoderado" (
  "estudiante_id" BIGINT NOT NULL,
  "apoderado_id" BIGINT NOT NULL,
  "parentesco" VARCHAR(50) NOT NULL,
  "es_principal" BOOLEAN NOT NULL DEFAULT false,
  "autorizado_recoger" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("estudiante_id", "apoderado_id")
);

CREATE TABLE "maestros" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "especialidad" VARCHAR(100),
  "fecha_contratacion" DATE NOT NULL,
  "fecha_retiro" DATE,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'inactivo', 'retirado')) DEFAULT 'activo',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "periodos_academicos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" INT NOT NULL,
  "nombre" VARCHAR(50) NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE NOT NULL,
  "activo" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "cursos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel" VARCHAR(30) NOT NULL CHECK (nivel IN ('inicial', 'primaria', 'secundaria', 'bachillerato')),
  "grado" VARCHAR(20) NOT NULL,
  "paralelo" VARCHAR(10) NOT NULL,
  "capacidad_maxima" INT NOT NULL DEFAULT 30,
  "activo" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "cursos_periodo" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_id" BIGINT NOT NULL,
  "periodo_id" BIGINT NOT NULL,
  "capacidad_maxima" INT NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'cerrado', 'cancelado')) DEFAULT 'activo'
);

CREATE TABLE "inscripciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "curso_periodo_id" BIGINT NOT NULL,
  "fecha_inscripcion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_retiro" TIMESTAMPTZ,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'retirado', 'finalizado')) DEFAULT 'activo',
  "observacion" TEXT
);

CREATE TABLE "materias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR(20) UNIQUE NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  "descripcion" TEXT,
  "activo" BOOLEAN NOT NULL DEFAULT true,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "asignaciones_docentes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "maestro_id" BIGINT NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "curso_periodo_id" BIGINT NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'finalizado', 'cancelado')) DEFAULT 'activo',
  "fecha_asignacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_finalizacion" TIMESTAMPTZ
);

CREATE TABLE "materia_materiales" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asignacion_id" BIGINT NOT NULL,
  "titulo" VARCHAR(250) NOT NULL,
  "detalle" TEXT,
  "archivo_url" VARCHAR(500) NOT NULL,
  "nombre_archivo" VARCHAR(255),
  "tipo_mime" VARCHAR(100),
  "tamanio_bytes" BIGINT,
  "fecha_subida" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "activo" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "curso_asesor" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_periodo_id" BIGINT NOT NULL,
  "maestro_id" BIGINT NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE
);

CREATE TABLE "encargos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asignacion_id" BIGINT NOT NULL,
  "tipo" VARCHAR(30) NOT NULL,
  "titulo" VARCHAR(150) NOT NULL,
  "descripcion" TEXT,
  "ponderacion" DECIMAL(5,2) NOT NULL CHECK (ponderacion > 0 AND ponderacion <= 100),
  "fecha_publicacion" TIMESTAMPTZ,
  "fecha_limite" TIMESTAMPTZ,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('borrador', 'publicado', 'cerrado', 'cancelado')) DEFAULT 'borrador',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "encargo_materiales" (
  "encargo_id" BIGINT NOT NULL,
  "material_id" BIGINT NOT NULL,
  PRIMARY KEY ("encargo_id", "material_id")
);

CREATE TABLE "encargo_entregas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "encargo_id" BIGINT NOT NULL,
  "estudiante_id" BIGINT NOT NULL,
  "archivo_url" VARCHAR(500) NOT NULL,
  "nombre_archivo" VARCHAR(255),
  "tipo_mime" VARCHAR(100),
  "tamanio_bytes" BIGINT,
  "comentario" TEXT,
  "fecha_entrega" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "estado_entrega" VARCHAR(20) NOT NULL CHECK (estado_entrega IN ('a_tiempo', 'con_retraso')) DEFAULT 'a_tiempo',
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_encargo_estudiante_entrega" UNIQUE ("encargo_id", "estudiante_id")
);

CREATE TABLE "calificaciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "encargo_id" BIGINT NOT NULL,
  "estudiante_id" BIGINT NOT NULL,
  "nota" DECIMAL(5,2) NOT NULL CHECK (nota >= 0 AND nota <= 100),
  "observacion" TEXT,
  "fecha_calificacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "asistencia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "asignacion_id" BIGINT NOT NULL,
  "fecha" DATE NOT NULL,
  "estado" VARCHAR(15) NOT NULL CHECK (estado IN ('presente', 'ausente', 'atraso', 'justificado')),
  "justificacion" TEXT,
  "fecha_registro" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "pensiones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "periodo_id" BIGINT NOT NULL,
  "concepto" VARCHAR(50) NOT NULL,
  "mes" SMALLINT,
  "monto" DECIMAL(10,2) NOT NULL CHECK (monto > 0),
  "fecha_vencimiento" DATE NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('pendiente', 'pagado', 'vencido', 'anulado')) DEFAULT 'pendiente',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "pagos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "monto" DECIMAL(10,2) NOT NULL CHECK (monto > 0),
  "metodo" VARCHAR(30) NOT NULL,
  "numero_transaccion" VARCHAR(100),
  "comprobante_url" VARCHAR(500),
  "fecha_pago" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "registrado_por" BIGINT NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('pendiente', 'confirmado', 'anulado')) DEFAULT 'confirmado',
  "observacion" TEXT
);

CREATE TABLE "pago_pensiones" (
  "pago_id" BIGINT NOT NULL,
  "pension_id" BIGINT NOT NULL,
  "monto" DECIMAL(10,2) NOT NULL CHECK (monto > 0),
  PRIMARY KEY ("pago_id", "pension_id")
);


-- ÍNDICES COMPUESTOS Y ADICIONALES PARA ESCALABILIDAD
CREATE INDEX "idx_usuarios_rol" ON "usuarios" ("rol_id");
CREATE INDEX "idx_usuarios_apellido" ON "usuarios" ("apellido_paterno");
CREATE INDEX "idx_usuarios_estado" ON "usuarios" ("estado");
-- Nuevo: Búsqueda rápida por combinación de nombre/apellido (pantallas de lista)
CREATE INDEX "idx_usuarios_nombre_completo" ON "usuarios" ("apellido_paterno", "nombre");

CREATE UNIQUE INDEX "uq_usuario_username" ON "usuario_cuenta" ("username");
CREATE UNIQUE INDEX "uq_usuario_email" ON "usuario_cuenta" ("email");

CREATE INDEX "idx_documentos_usuario" ON "usuario_documentos" ("usuario_id");
CREATE INDEX "idx_contactos_usuario" ON "usuario_contactos" ("usuario_id");
CREATE INDEX "idx_contactos_tipo" ON "usuario_contactos" ("tipo");

CREATE INDEX "idx_estudiante_estado" ON "estudiantes" ("estado");
CREATE INDEX "idx_estudiante_usuario" ON "estudiantes" ("usuario_id");

CREATE INDEX "idx_estudiante_apoderado" ON "estudiante_apoderado" ("estudiante_id");
CREATE INDEX "idx_apoderado_estudiante" ON "estudiante_apoderado" ("apoderado_id");

CREATE INDEX "idx_maestro_estado" ON "maestros" ("estado");
CREATE INDEX "idx_maestro_usuario" ON "maestros" ("usuario_id");

CREATE UNIQUE INDEX "uq_periodo_anio_nombre" ON "periodos_academicos" ("anio", "nombre");
CREATE INDEX "idx_periodo_activo" ON "periodos_academicos" ("activo");

CREATE UNIQUE INDEX "uq_curso" ON "cursos" ("nivel", "grado", "paralelo");

CREATE UNIQUE INDEX "uq_curso_periodo" ON "cursos_periodo" ("curso_id", "periodo_id");
CREATE INDEX "idx_curso_periodo_curso" ON "cursos_periodo" ("curso_id");
CREATE INDEX "idx_curso_periodo_periodo" ON "cursos_periodo" ("periodo_id");

CREATE UNIQUE INDEX "uq_inscripcion" ON "inscripciones" ("estudiante_id", "curso_periodo_id");
CREATE INDEX "idx_inscripcion_estudiante" ON "inscripciones" ("estudiante_id");
CREATE INDEX "idx_inscripcion_curso" ON "inscripciones" ("curso_periodo_id");
CREATE INDEX "idx_inscripcion_estado" ON "inscripciones" ("estado");

CREATE INDEX "idx_materia_nombre" ON "materias" ("nombre");

CREATE UNIQUE INDEX "uq_asignacion_docente" ON "asignaciones_docentes" ("maestro_id", "materia_id", "curso_periodo_id");
CREATE INDEX "idx_asignacion_maestro" ON "asignaciones_docentes" ("maestro_id");
CREATE INDEX "idx_asignacion_materia" ON "asignaciones_docentes" ("materia_id");
CREATE INDEX "idx_asignacion_curso" ON "asignaciones_docentes" ("curso_periodo_id");

CREATE INDEX "idx_material_asignacion" ON "materia_materiales" ("asignacion_id");

CREATE UNIQUE INDEX "uq_curso_asesor" ON "curso_asesor" ("curso_periodo_id");
CREATE INDEX "idx_asesor_maestro" ON "curso_asesor" ("maestro_id");

CREATE INDEX "idx_encargo_asignacion" ON "encargos" ("asignacion_id");
CREATE INDEX "idx_encargo_estado" ON "encargos" ("estado");
CREATE INDEX "idx_encargo_fecha_limite" ON "encargos" ("fecha_limite");

CREATE UNIQUE INDEX "uq_calificacion" ON "calificaciones" ("encargo_id", "estudiante_id");
CREATE INDEX "idx_calificacion_estudiante" ON "calificaciones" ("estudiante_id");
CREATE INDEX "idx_calificacion_encargo" ON "calificaciones" ("encargo_id");

CREATE UNIQUE INDEX "uq_asistencia" ON "asistencia" ("estudiante_id", "asignacion_id", "fecha");
CREATE INDEX "idx_asistencia_fecha" ON "asistencia" ("fecha", "asignacion_id");
CREATE INDEX "idx_asistencia_estudiante" ON "asistencia" ("estudiante_id");
CREATE INDEX "idx_asistencia_asignacion" ON "asistencia" ("asignacion_id");

CREATE UNIQUE INDEX "uq_pension" ON "pensiones" ("estudiante_id", "periodo_id", "concepto", "mes");
CREATE INDEX "idx_pension_estudiante" ON "pensiones" ("estudiante_id");
CREATE INDEX "idx_pension_periodo" ON "pensiones" ("periodo_id");
CREATE INDEX "idx_pension_estado" ON "pensiones" ("estado");
CREATE INDEX "idx_pension_vencimiento" ON "pensiones" ("fecha_vencimiento");

CREATE UNIQUE INDEX "uq_pago_transaccion" ON "pagos" ("numero_transaccion");
CREATE INDEX "idx_pago_estudiante" ON "pagos" ("estudiante_id");
CREATE INDEX "idx_pago_registrado_por" ON "pagos" ("registrado_por");
CREATE INDEX "idx_pago_fecha" ON "pagos" ("fecha_pago");
CREATE INDEX "idx_pago_estado" ON "pagos" ("estado");

CREATE INDEX "idx_pago_pension_pago" ON "pago_pensiones" ("pago_id");
CREATE INDEX "idx_pago_pension_pension" ON "pago_pensiones" ("pension_id");

-- =============================================================================
-- LLAVES FORÁNEAS (RESTRICT vs CASCADE)
-- =============================================================================

-- Estructura Core de Usuarios
ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id") ON DELETE RESTRICT;
ALTER TABLE "usuario_cuenta" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;
ALTER TABLE "usuario_documentos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;
ALTER TABLE "usuario_direcciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;
ALTER TABLE "usuario_contactos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;

-- Entidades de Dominio de Usuario
ALTER TABLE "estudiantes" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;
ALTER TABLE "apoderados" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;
ALTER TABLE "maestros" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;

-- Tabla Relacional Estudiante-Apoderado
ALTER TABLE "estudiante_apoderado" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE CASCADE;
ALTER TABLE "estudiante_apoderado" ADD FOREIGN KEY ("apoderado_id") REFERENCES "apoderados" ("id") ON DELETE CASCADE;

-- Estructura Académica
ALTER TABLE "cursos_periodo" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("id") ON DELETE RESTRICT;
ALTER TABLE "cursos_periodo" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE RESTRICT;

ALTER TABLE "inscripciones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "inscripciones" ADD FOREIGN KEY ("curso_periodo_id") REFERENCES "cursos_periodo" ("id") ON DELETE RESTRICT;

ALTER TABLE "asignaciones_docentes" ADD FOREIGN KEY ("maestro_id") REFERENCES "maestros" ("id") ON DELETE RESTRICT;
ALTER TABLE "asignaciones_docentes" ADD FOREIGN KEY ("materia_id") REFERENCES "materias" ("id") ON DELETE RESTRICT;
ALTER TABLE "asignaciones_docentes" ADD FOREIGN KEY ("curso_periodo_id") REFERENCES "cursos_periodo" ("id") ON DELETE RESTRICT;

ALTER TABLE "materia_materiales" ADD FOREIGN KEY ("asignacion_id") REFERENCES "asignaciones_docentes" ("id") ON DELETE CASCADE;

ALTER TABLE "curso_asesor" ADD FOREIGN KEY ("curso_periodo_id") REFERENCES "cursos_periodo" ("id") ON DELETE RESTRICT;
ALTER TABLE "curso_asesor" ADD FOREIGN KEY ("maestro_id") REFERENCES "maestros" ("id") ON DELETE RESTRICT;

ALTER TABLE "encargos" ADD FOREIGN KEY ("asignacion_id") REFERENCES "asignaciones_docentes" ("id") ON DELETE CASCADE;

ALTER TABLE "encargo_materiales" ADD FOREIGN KEY ("encargo_id") REFERENCES "encargos" ("id") ON DELETE CASCADE;
ALTER TABLE "encargo_materiales" ADD FOREIGN KEY ("material_id") REFERENCES "materia_materiales" ("id") ON DELETE CASCADE;

-- Evaluaciones y Asistencia
ALTER TABLE "calificaciones" ADD FOREIGN KEY ("encargo_id") REFERENCES "encargos" ("id") ON DELETE RESTRICT;
ALTER TABLE "calificaciones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "asistencia" ADD FOREIGN KEY ("asignacion_id") REFERENCES "asignaciones_docentes" ("id") ON DELETE RESTRICT;

-- Módulo Financiero
ALTER TABLE "pensiones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "pensiones" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE RESTRICT;

ALTER TABLE "pagos" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "pagos" ADD FOREIGN KEY ("registrado_por") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;

ALTER TABLE "pago_pensiones" ADD FOREIGN KEY ("pago_id") REFERENCES "pagos" ("id") ON DELETE CASCADE;
ALTER TABLE "pago_pensiones" ADD FOREIGN KEY ("pension_id") REFERENCES "pensiones" ("id") ON DELETE RESTRICT;