
-- TABLAS
CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" VARCHAR(50) UNIQUE NOT NULL,
  "descripcion" VARCHAR(255),
  "activo" BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO "roles" ("rol", "descripcion")
VALUES
  ('director', 'Dirección General'),
  ('profesor', 'Personal docente'),
  ('estudiante', 'Estudiante'),
  ('control', 'Control / Administración'),
  ('apoderado', 'Apoderado / Tutor'),
  ('gerencia', 'Gerencia')
ON CONFLICT ("rol") DO UPDATE SET "descripcion" = EXCLUDED."descripcion", "activo" = true;

CREATE TABLE "usuarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol_id" BIGINT NOT NULL,
  "nombre" VARCHAR(80) NOT NULL,
  "apellido_paterno" VARCHAR(80) NOT NULL,
  "apellido_materno" VARCHAR(80),
  "nacimiento" DATE NOT NULL,
  "genero" VARCHAR(15) CHECK (genero IN ('masculino', 'femenino', 'otro')),
  "foto_url" VARCHAR(500),
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'inactivo', 'bloqueado')) DEFAULT 'activo',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_cuenta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "username" VARCHAR(100) UNIQUE NOT NULL,
  "email" VARCHAR(150) UNIQUE,
  "password_hash" VARCHAR(255) NOT NULL,
  "email_verificado" BOOLEAN NOT NULL DEFAULT false,
  "primer_login" BOOLEAN NOT NULL DEFAULT true,
  "datos_personales_actualizados" BOOLEAN NOT NULL DEFAULT false,
  "contacto_tutor_actualizado" BOOLEAN NOT NULL DEFAULT false,
  "password_actualizado" BOOLEAN NOT NULL DEFAULT false,
  "ultimo_login" TIMESTAMPTZ,
  "intentos_fallidos" SMALLINT NOT NULL DEFAULT 0,
  "bloqueado_hasta" TIMESTAMPTZ,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_documentos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "tipo_doc" VARCHAR(30) NOT NULL,
  "numero_doc" VARCHAR(50) UNIQUE NOT NULL,
  "doc_url" VARCHAR(500),
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_direcciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "zona" VARCHAR(90) NOT NULL,
  "distrito" VARCHAR(100),
  "bloque" VARCHAR(100),
  "calle" VARCHAR(100),
  "numero" VARCHAR(50),
  "edificio" VARCHAR(100),
  "piso" INT,
  "referencia" TEXT,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "usuario_contactos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT NOT NULL,
  "tipo" VARCHAR(30) NOT NULL,
  "contenido" VARCHAR(200) NOT NULL,
  "principal" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "estudiantes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "fecha_ingreso" DATE NOT NULL,
  "tutor_nombre" VARCHAR(120),
  "tutor_telefono" VARCHAR(30),
  "tutor_parentesco" VARCHAR(50),
  "fecha_egreso" DATE,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'retirado', 'egresado', 'suspendido')) DEFAULT 'activo',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "apoderados" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "ocupacion" VARCHAR(100),
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "estudiante_apoderado" (
  "estudiante_id" BIGINT NOT NULL,
  "apoderado_id" BIGINT NOT NULL,
  "parentesco" VARCHAR(50) NOT NULL,
  "es_principal" BOOLEAN NOT NULL DEFAULT false,
  "autorizado_recoger" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("estudiante_id", "apoderado_id")
);

CREATE TABLE "maestros" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" BIGINT UNIQUE NOT NULL,
  "especialidad" VARCHAR(100),
  "fecha_contratacion" DATE NOT NULL,
  "materias_configuradas" BOOLEAN NOT NULL DEFAULT false,
  "fecha_retiro" DATE,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'inactivo', 'retirado')) DEFAULT 'activo',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Materias que un docente está habilitado a impartir. La asignación a un
-- curso/paralelo se guarda posteriormente en asignaciones_docentes.
CREATE TABLE "maestro_materias" (
  "maestro_id" BIGINT NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "fecha_asignacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("maestro_id", "materia_id")
);

CREATE TABLE "periodos_academicos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" INT NOT NULL,
  "nombre" VARCHAR(50) NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE NOT NULL,
  "inicio_gestion" DATE NOT NULL,
  "fin_gestion" DATE NOT NULL,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'configuracion' CONSTRAINT "chk_periodo_estado" CHECK (estado IN ('borrador', 'configuracion', 'activo', 'cerrado', 'cancelado')),
  "origen_periodo_id" BIGINT,
  "estructura_generada" BOOLEAN NOT NULL DEFAULT false,
  "horarios_generados" BOOLEAN NOT NULL DEFAULT false,
  "plan_pagos_generado" BOOLEAN NOT NULL DEFAULT false,
  "activado_at" TIMESTAMPTZ,
  "activo" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_periodo_gestion_fechas" CHECK ("fin_gestion" > "inicio_gestion"),
  CONSTRAINT "chk_periodo_fechas" CHECK ("fecha_fin" > "fecha_inicio")
);

CREATE TABLE "trimestres" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "periodo_id" BIGINT NOT NULL,
  "numero" SMALLINT NOT NULL CHECK ("numero" BETWEEN 1 AND 3),
  "inicio" DATE NOT NULL,
  "fin" DATE NOT NULL,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_trimestre_periodo_numero" UNIQUE ("periodo_id", "numero"),
  CONSTRAINT "chk_trimestre_fechas" CHECK ("fin" >= "inicio")
);

CREATE TABLE "cursos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel" VARCHAR(30) NOT NULL CHECK (nivel IN ('inicial', 'primaria', 'secundaria', 'bachillerato')),
  "grado" VARCHAR(20) NOT NULL,
  "paralelo" VARCHAR(10) NOT NULL,
  "capacidad_maxima" INT NOT NULL DEFAULT 30 CHECK ("capacidad_maxima" > 0),
  "activo" BOOLEAN NOT NULL DEFAULT true,
  "caratula_url" VARCHAR(500)
);

CREATE TABLE "turnos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR(20) UNIQUE NOT NULL CHECK (codigo IN ('manana', 'tarde')),
  "nombre" VARCHAR(50) NOT NULL,
  "hora_inicio" TIME NOT NULL,
  "hora_fin" TIME NOT NULL,
  "receso_inicio" TIME NOT NULL,
  "receso_fin" TIME NOT NULL,
  "duracion_periodo_minutos" SMALLINT NOT NULL DEFAULT 45 CHECK ("duracion_periodo_minutos" IN (45, 50)),
  "activo" BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO "turnos" ("codigo", "nombre", "hora_inicio", "hora_fin", "receso_inicio", "receso_fin")
VALUES
  ('manana', 'Turno Mañana', '07:00', '12:30', '09:30', '10:00'),
  ('tarde', 'Turno Tarde', '14:00', '18:30', '16:00', '16:30')
ON CONFLICT ("codigo") DO UPDATE SET
  "nombre" = EXCLUDED."nombre",
  "hora_inicio" = EXCLUDED."hora_inicio",
  "hora_fin" = EXCLUDED."hora_fin",
  "receso_inicio" = EXCLUDED."receso_inicio",
  "receso_fin" = EXCLUDED."receso_fin";

CREATE TABLE "cursos_periodo" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_id" BIGINT NOT NULL,
  "periodo_id" BIGINT NOT NULL,
  "capacidad_maxima" INT NOT NULL CHECK ("capacidad_maxima" > 0),
  "turno_id" BIGINT NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'cerrado', 'cancelado')) DEFAULT 'activo'
);

CREATE TABLE "inscripciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "curso_periodo_id" BIGINT NOT NULL,
  "periodo_id" BIGINT NOT NULL,
  "solicitud_id" BIGINT,
  "origen" VARCHAR(20) NOT NULL DEFAULT 'nueva' CHECK (origen IN ('nueva', 'reserva', 'promocion')),
  "fecha_inscripcion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_retiro" TIMESTAMPTZ,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'retirado', 'finalizado')) DEFAULT 'activo',
  "observacion" TEXT
);

CREATE TABLE "solicitudes_inscripcion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "periodo_id" BIGINT NOT NULL,
  "curso_periodo_destino_id" BIGINT NOT NULL,
  "tipo" VARCHAR(20) NOT NULL CHECK (tipo IN ('reserva', 'promocion')),
  "estado" VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aprobada', 'rechazada')),
  "motivo" TEXT,
  "solicitante_id" BIGINT,
  "procesado_por" BIGINT,
  "fecha_solicitud" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_proceso" TIMESTAMPTZ,
  "observacion" TEXT
);

CREATE TABLE "materias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR(20) UNIQUE NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  "descripcion" TEXT,
  "tipo_materia" VARCHAR(20) NOT NULL DEFAULT 'principal' CHECK (tipo_materia IN ('principal', 'extracurricular')),
  "carga_horaria_semanal" SMALLINT NOT NULL DEFAULT 5 CHECK ("carga_horaria_semanal" > 0),
  "peso_sintactico" SMALLINT NOT NULL DEFAULT 3 CHECK ("peso_sintactico" > 0),
  "materia_pesada" BOOLEAN NOT NULL DEFAULT false,
  "activo" BOOLEAN NOT NULL DEFAULT true,
  "caratula_url" VARCHAR(500),
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "aulas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR(30) UNIQUE NOT NULL,
  "nombre" VARCHAR(80) NOT NULL,
  "capacidad" INT NOT NULL DEFAULT 30 CHECK ("capacidad" > 0),
  "activa" BOOLEAN NOT NULL DEFAULT true,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "mallas_curriculares" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "periodo_id" BIGINT NOT NULL,
  "nivel" VARCHAR(30) NOT NULL CHECK (nivel IN ('inicial', 'primaria', 'secundaria', 'bachillerato')),
  "grado" VARCHAR(20) NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "tipo_materia" VARCHAR(20) NOT NULL CHECK (tipo_materia IN ('principal', 'extracurricular')),
  "carga_horaria_semanal" SMALLINT NOT NULL CHECK ("carga_horaria_semanal" > 0),
  "peso_sintactico" SMALLINT NOT NULL DEFAULT 1 CHECK ("peso_sintactico" > 0),
  "activo" BOOLEAN NOT NULL DEFAULT true,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_malla_periodo_grado_materia" UNIQUE ("periodo_id", "nivel", "grado", "materia_id")
);

CREATE TABLE "asignaciones_docentes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "maestro_id" BIGINT NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "curso_periodo_id" BIGINT NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('activo', 'finalizado', 'cancelado')) DEFAULT 'activo',
  "fecha_asignacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_finalizacion" TIMESTAMPTZ
);

CREATE TABLE "horarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_periodo_id" BIGINT NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "asignacion_id" BIGINT,
  "maestro_id" BIGINT,
  "aula_id" BIGINT NOT NULL,
  "turno_id" BIGINT NOT NULL,
  "dia_semana" SMALLINT NOT NULL CHECK ("dia_semana" BETWEEN 1 AND 5),
  "hora_inicio" TIME NOT NULL,
  "hora_fin" TIME NOT NULL,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'cancelado')),
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_horario_hora" CHECK ("hora_fin" > "hora_inicio")
);

CREATE TABLE "planes_pago" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "periodo_id" BIGINT NOT NULL,
  "nivel" VARCHAR(30) NOT NULL DEFAULT 'general',
  "nombre" VARCHAR(80) NOT NULL,
  "cantidad_cuotas" SMALLINT NOT NULL CHECK ("cantidad_cuotas" > 0),
  "monto_total" DECIMAL(12,2) NOT NULL CHECK ("monto_total" > 0),
  "monto_cuota" DECIMAL(12,2) NOT NULL CHECK ("monto_cuota" > 0),
  "dia_vencimiento" SMALLINT NOT NULL DEFAULT 10 CHECK ("dia_vencimiento" BETWEEN 1 AND 28),
  "estado" VARCHAR(20) NOT NULL DEFAULT 'generado' CHECK (estado IN ('borrador', 'generado', 'anulado')),
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_plan_periodo_nivel" UNIQUE ("periodo_id", "nivel")
);

CREATE TABLE "cuotas_plan_pago" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plan_id" BIGINT NOT NULL,
  "numero" SMALLINT NOT NULL CHECK ("numero" > 0),
  "anio" SMALLINT NOT NULL,
  "mes" SMALLINT NOT NULL CHECK ("mes" BETWEEN 1 AND 12),
  "fecha_vencimiento" DATE NOT NULL,
  "monto" DECIMAL(12,2) NOT NULL CHECK ("monto" > 0),
  "estado" VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'pagado', 'anulado')),
  CONSTRAINT "uq_cuota_plan_numero" UNIQUE ("plan_id", "numero")
);

CREATE TABLE "materia_materiales" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asignacion_id" BIGINT NOT NULL,
  "titulo" VARCHAR(250) NOT NULL,
  "detalle" TEXT,
  "archivo_url" VARCHAR(500) NOT NULL,
  "nombre_archivo" VARCHAR(255),
  "tipo_mime" VARCHAR(100),
  "tamanio_bytes" BIGINT,
  "fecha_subida" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "activo" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "curso_asesor" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_periodo_id" BIGINT NOT NULL,
  "maestro_id" BIGINT NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE
);

CREATE TABLE "encargos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asignacion_id" BIGINT NOT NULL,
  "tipo" VARCHAR(30) NOT NULL,
  "titulo" VARCHAR(150) NOT NULL,
  "descripcion" TEXT,
  "ponderacion" DECIMAL(5,2) NOT NULL CHECK (ponderacion > 0 AND ponderacion <= 100),
  "fecha_publicacion" TIMESTAMPTZ,
  "fecha_limite" TIMESTAMPTZ,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('borrador', 'publicado', 'cerrado', 'cancelado')) DEFAULT 'borrador',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "encargo_materiales" (
  "encargo_id" BIGINT NOT NULL,
  "material_id" BIGINT NOT NULL,
  PRIMARY KEY ("encargo_id", "material_id")
);

CREATE TABLE "encargo_entregas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "encargo_id" BIGINT NOT NULL,
  "estudiante_id" BIGINT NOT NULL,
  "archivo_url" VARCHAR(500) NOT NULL,
  "nombre_archivo" VARCHAR(255),
  "tipo_mime" VARCHAR(100),
  "tamanio_bytes" BIGINT,
  "comentario" TEXT,
  "fecha_entrega" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "estado_entrega" VARCHAR(20) NOT NULL CHECK (estado_entrega IN ('a_tiempo', 'con_retraso')) DEFAULT 'a_tiempo',
  CONSTRAINT "uq_encargo_estudiante_entrega" UNIQUE ("encargo_id", "estudiante_id")
);

CREATE TABLE "calificaciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "encargo_id" BIGINT NOT NULL,
  "estudiante_id" BIGINT NOT NULL,
  "nota" DECIMAL(5,2) NOT NULL CHECK (nota >= 0 AND nota <= 100),
  "observacion" TEXT,
  "fecha_calificacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "asistencia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "asignacion_id" BIGINT NOT NULL,
  "fecha" DATE NOT NULL,
  "estado" VARCHAR(15) NOT NULL CHECK (estado IN ('presente', 'ausente', 'atraso', 'justificado')),
  "justificacion" TEXT,
  "fecha_registro" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "pensiones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "periodo_id" BIGINT NOT NULL,
  "plan_pago_id" BIGINT,
  "numero_cuota" SMALLINT,
  "concepto" VARCHAR(50) NOT NULL,
  "mes" SMALLINT,
  "monto" DECIMAL(10,2) NOT NULL CHECK (monto > 0),
  "fecha_vencimiento" DATE NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('pendiente', 'pagado', 'vencido', 'anulado')) DEFAULT 'pendiente',
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "pagos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" BIGINT NOT NULL,
  "monto" DECIMAL(10,2) NOT NULL CHECK (monto > 0),
  "metodo" VARCHAR(30) NOT NULL,
  "numero_transaccion" VARCHAR(100),
  "comprobante_url" VARCHAR(500),
  "fecha_pago" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "registrado_por" BIGINT NOT NULL,
  "estado" VARCHAR(20) NOT NULL CHECK (estado IN ('pendiente', 'confirmado', 'anulado')) DEFAULT 'confirmado',
  "observacion" TEXT
);

CREATE TABLE "pago_pensiones" (
  "pago_id" BIGINT NOT NULL,
  "pension_id" BIGINT NOT NULL,
  "monto" DECIMAL(10,2) NOT NULL CHECK (monto > 0),
  PRIMARY KEY ("pago_id", "pension_id")
);


-- ÍNDICES COMPUESTOS Y ADICIONALES PARA ESCALABILIDAD
CREATE INDEX "idx_usuarios_rol" ON "usuarios" ("rol_id");
CREATE INDEX "idx_usuarios_apellido" ON "usuarios" ("apellido_paterno");
CREATE INDEX "idx_usuarios_estado" ON "usuarios" ("estado");
-- Nuevo: Búsqueda rápida por combinación de nombre/apellido (pantallas de lista)
CREATE INDEX "idx_usuarios_nombre_completo" ON "usuarios" ("apellido_paterno", "nombre");

CREATE UNIQUE INDEX "uq_usuario_username" ON "usuario_cuenta" ("username");
CREATE UNIQUE INDEX "uq_usuario_email" ON "usuario_cuenta" ("email");

CREATE INDEX "idx_documentos_usuario" ON "usuario_documentos" ("usuario_id");
CREATE INDEX "idx_contactos_usuario" ON "usuario_contactos" ("usuario_id");
CREATE INDEX "idx_contactos_tipo" ON "usuario_contactos" ("tipo");

CREATE INDEX "idx_estudiante_estado" ON "estudiantes" ("estado");
CREATE INDEX "idx_estudiante_usuario" ON "estudiantes" ("usuario_id");

CREATE INDEX "idx_estudiante_apoderado" ON "estudiante_apoderado" ("estudiante_id");
CREATE INDEX "idx_apoderado_estudiante" ON "estudiante_apoderado" ("apoderado_id");

CREATE INDEX "idx_maestro_estado" ON "maestros" ("estado");
CREATE INDEX "idx_maestro_usuario" ON "maestros" ("usuario_id");
CREATE INDEX "idx_maestro_materias_materia" ON "maestro_materias" ("materia_id");

CREATE UNIQUE INDEX "uq_periodo_anio_nombre" ON "periodos_academicos" ("anio", "nombre");
CREATE INDEX "idx_periodo_activo" ON "periodos_academicos" ("activo");
CREATE UNIQUE INDEX "uq_periodo_activo" ON "periodos_academicos" ("activo") WHERE "activo" = true;
CREATE INDEX "idx_trimestre_periodo" ON "trimestres" ("periodo_id", "numero");
CREATE INDEX "idx_turno_activo" ON "turnos" ("activo");

CREATE UNIQUE INDEX "uq_curso" ON "cursos" ("nivel", "grado", "paralelo");

CREATE UNIQUE INDEX "uq_curso_periodo" ON "cursos_periodo" ("curso_id", "periodo_id");
CREATE UNIQUE INDEX "uq_curso_periodo_id_periodo" ON "cursos_periodo" ("id", "periodo_id");
CREATE INDEX "idx_curso_periodo_curso" ON "cursos_periodo" ("curso_id");
CREATE INDEX "idx_curso_periodo_periodo" ON "cursos_periodo" ("periodo_id");

CREATE UNIQUE INDEX "uq_inscripcion" ON "inscripciones" ("estudiante_id", "curso_periodo_id");
CREATE INDEX "idx_inscripcion_estudiante" ON "inscripciones" ("estudiante_id");
CREATE INDEX "idx_inscripcion_curso" ON "inscripciones" ("curso_periodo_id");
CREATE INDEX "idx_inscripcion_estado" ON "inscripciones" ("estado");
CREATE UNIQUE INDEX "uq_inscripcion_solicitud" ON "inscripciones" ("solicitud_id") WHERE "solicitud_id" IS NOT NULL;
CREATE UNIQUE INDEX "uq_inscripcion_activa_periodo" ON "inscripciones" ("estudiante_id", "periodo_id") WHERE "estado" = 'activo';

CREATE INDEX "idx_materia_nombre" ON "materias" ("nombre");
CREATE INDEX "idx_malla_periodo_grado" ON "mallas_curriculares" ("periodo_id", "nivel", "grado");
CREATE INDEX "idx_aula_activa" ON "aulas" ("activa");

CREATE UNIQUE INDEX "uq_asignacion_docente" ON "asignaciones_docentes" ("maestro_id", "materia_id", "curso_periodo_id");
CREATE INDEX "idx_asignacion_maestro" ON "asignaciones_docentes" ("maestro_id");
CREATE INDEX "idx_asignacion_materia" ON "asignaciones_docentes" ("materia_id");
CREATE INDEX "idx_asignacion_curso" ON "asignaciones_docentes" ("curso_periodo_id");
CREATE INDEX "idx_horario_curso_bloque" ON "horarios" ("curso_periodo_id", "dia_semana", "hora_inicio");
CREATE INDEX "idx_horario_docente_bloque" ON "horarios" ("maestro_id", "dia_semana", "hora_inicio");
CREATE INDEX "idx_horario_aula_bloque" ON "horarios" ("aula_id", "dia_semana", "hora_inicio");
CREATE INDEX "idx_plan_periodo" ON "planes_pago" ("periodo_id");
CREATE INDEX "idx_cuota_plan" ON "cuotas_plan_pago" ("plan_id", "numero");
CREATE INDEX "idx_solicitud_estudiante" ON "solicitudes_inscripcion" ("estudiante_id", "estado");
CREATE UNIQUE INDEX "uq_solicitud_pendiente" ON "solicitudes_inscripcion" ("estudiante_id", "curso_periodo_destino_id") WHERE "estado" = 'pendiente';

CREATE INDEX "idx_material_asignacion" ON "materia_materiales" ("asignacion_id");

CREATE UNIQUE INDEX "uq_curso_asesor" ON "curso_asesor" ("curso_periodo_id");
CREATE INDEX "idx_asesor_maestro" ON "curso_asesor" ("maestro_id");

CREATE INDEX "idx_encargo_asignacion" ON "encargos" ("asignacion_id");
CREATE INDEX "idx_encargo_estado" ON "encargos" ("estado");
CREATE INDEX "idx_encargo_fecha_limite" ON "encargos" ("fecha_limite");

CREATE UNIQUE INDEX "uq_calificacion" ON "calificaciones" ("encargo_id", "estudiante_id");
CREATE INDEX "idx_calificacion_estudiante" ON "calificaciones" ("estudiante_id");
CREATE INDEX "idx_calificacion_encargo" ON "calificaciones" ("encargo_id");

CREATE UNIQUE INDEX "uq_asistencia" ON "asistencia" ("estudiante_id", "asignacion_id", "fecha");
CREATE INDEX "idx_asistencia_fecha" ON "asistencia" ("fecha", "asignacion_id");
CREATE INDEX "idx_asistencia_estudiante" ON "asistencia" ("estudiante_id");
CREATE INDEX "idx_asistencia_asignacion" ON "asistencia" ("asignacion_id");

CREATE UNIQUE INDEX "uq_pension" ON "pensiones" ("estudiante_id", "periodo_id", "concepto", "mes");
CREATE INDEX "idx_pension_estudiante" ON "pensiones" ("estudiante_id");
CREATE INDEX "idx_pension_periodo" ON "pensiones" ("periodo_id");
CREATE INDEX "idx_pension_plan" ON "pensiones" ("plan_pago_id", "numero_cuota");
CREATE UNIQUE INDEX "uq_pension_plan_cuota" ON "pensiones" ("plan_pago_id", "estudiante_id", "numero_cuota") WHERE "plan_pago_id" IS NOT NULL;
CREATE INDEX "idx_pension_estado" ON "pensiones" ("estado");
CREATE INDEX "idx_pension_vencimiento" ON "pensiones" ("fecha_vencimiento");

CREATE UNIQUE INDEX "uq_pago_transaccion" ON "pagos" ("numero_transaccion");
CREATE INDEX "idx_pago_estudiante" ON "pagos" ("estudiante_id");
CREATE INDEX "idx_pago_registrado_por" ON "pagos" ("registrado_por");
CREATE INDEX "idx_pago_fecha" ON "pagos" ("fecha_pago");
CREATE INDEX "idx_pago_estado" ON "pagos" ("estado");

CREATE INDEX "idx_pago_pension_pago" ON "pago_pensiones" ("pago_id");
CREATE INDEX "idx_pago_pension_pension" ON "pago_pensiones" ("pension_id");

-- =============================================================================
-- LLAVES FORÁNEAS (RESTRICT vs CASCADE)
-- =============================================================================

-- Estructura Core de Usuarios
ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id") ON DELETE RESTRICT;
ALTER TABLE "usuario_cuenta" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;
ALTER TABLE "usuario_documentos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;
ALTER TABLE "usuario_direcciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;
ALTER TABLE "usuario_contactos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;

-- Entidades de Dominio de Usuario
ALTER TABLE "estudiantes" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;
ALTER TABLE "apoderados" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;
ALTER TABLE "maestros" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;
ALTER TABLE "maestro_materias" ADD FOREIGN KEY ("maestro_id") REFERENCES "maestros" ("id") ON DELETE CASCADE;
ALTER TABLE "maestro_materias" ADD FOREIGN KEY ("materia_id") REFERENCES "materias" ("id") ON DELETE RESTRICT;

-- Tabla Relacional Estudiante-Apoderado
ALTER TABLE "estudiante_apoderado" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE CASCADE;
ALTER TABLE "estudiante_apoderado" ADD FOREIGN KEY ("apoderado_id") REFERENCES "apoderados" ("id") ON DELETE CASCADE;

-- Estructura Académica
ALTER TABLE "periodos_academicos" ADD FOREIGN KEY ("origen_periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE SET NULL;
ALTER TABLE "trimestres" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE CASCADE;
ALTER TABLE "cursos_periodo" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("id") ON DELETE RESTRICT;
ALTER TABLE "cursos_periodo" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE RESTRICT;
ALTER TABLE "cursos_periodo" ADD FOREIGN KEY ("turno_id") REFERENCES "turnos" ("id") ON DELETE RESTRICT;
ALTER TABLE "mallas_curriculares" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE CASCADE;
ALTER TABLE "mallas_curriculares" ADD FOREIGN KEY ("materia_id") REFERENCES "materias" ("id") ON DELETE RESTRICT;

ALTER TABLE "inscripciones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "inscripciones" ADD FOREIGN KEY ("curso_periodo_id") REFERENCES "cursos_periodo" ("id") ON DELETE RESTRICT;
ALTER TABLE "inscripciones" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE RESTRICT;
ALTER TABLE "inscripciones" ADD FOREIGN KEY ("curso_periodo_id", "periodo_id") REFERENCES "cursos_periodo" ("id", "periodo_id") ON DELETE RESTRICT;
ALTER TABLE "inscripciones" ADD FOREIGN KEY ("solicitud_id") REFERENCES "solicitudes_inscripcion" ("id") ON DELETE SET NULL;

ALTER TABLE "horarios" ADD FOREIGN KEY ("curso_periodo_id") REFERENCES "cursos_periodo" ("id") ON DELETE CASCADE;
ALTER TABLE "horarios" ADD FOREIGN KEY ("materia_id") REFERENCES "materias" ("id") ON DELETE RESTRICT;
ALTER TABLE "horarios" ADD FOREIGN KEY ("asignacion_id") REFERENCES "asignaciones_docentes" ("id") ON DELETE SET NULL;
ALTER TABLE "horarios" ADD FOREIGN KEY ("maestro_id") REFERENCES "maestros" ("id") ON DELETE SET NULL;
ALTER TABLE "horarios" ADD FOREIGN KEY ("aula_id") REFERENCES "aulas" ("id") ON DELETE RESTRICT;
ALTER TABLE "horarios" ADD FOREIGN KEY ("turno_id") REFERENCES "turnos" ("id") ON DELETE RESTRICT;

ALTER TABLE "asignaciones_docentes" ADD FOREIGN KEY ("maestro_id") REFERENCES "maestros" ("id") ON DELETE RESTRICT;
ALTER TABLE "asignaciones_docentes" ADD FOREIGN KEY ("materia_id") REFERENCES "materias" ("id") ON DELETE RESTRICT;
ALTER TABLE "asignaciones_docentes" ADD FOREIGN KEY ("curso_periodo_id") REFERENCES "cursos_periodo" ("id") ON DELETE RESTRICT;

ALTER TABLE "solicitudes_inscripcion" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "solicitudes_inscripcion" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE RESTRICT;
ALTER TABLE "solicitudes_inscripcion" ADD FOREIGN KEY ("curso_periodo_destino_id") REFERENCES "cursos_periodo" ("id") ON DELETE RESTRICT;
ALTER TABLE "solicitudes_inscripcion" ADD FOREIGN KEY ("curso_periodo_destino_id", "periodo_id") REFERENCES "cursos_periodo" ("id", "periodo_id") ON DELETE RESTRICT;
ALTER TABLE "solicitudes_inscripcion" ADD FOREIGN KEY ("solicitante_id") REFERENCES "usuarios" ("id") ON DELETE SET NULL;
ALTER TABLE "solicitudes_inscripcion" ADD FOREIGN KEY ("procesado_por") REFERENCES "usuarios" ("id") ON DELETE SET NULL;

ALTER TABLE "materia_materiales" ADD FOREIGN KEY ("asignacion_id") REFERENCES "asignaciones_docentes" ("id") ON DELETE CASCADE;

ALTER TABLE "curso_asesor" ADD FOREIGN KEY ("curso_periodo_id") REFERENCES "cursos_periodo" ("id") ON DELETE RESTRICT;
ALTER TABLE "curso_asesor" ADD FOREIGN KEY ("maestro_id") REFERENCES "maestros" ("id") ON DELETE RESTRICT;

ALTER TABLE "encargos" ADD FOREIGN KEY ("asignacion_id") REFERENCES "asignaciones_docentes" ("id") ON DELETE CASCADE;

ALTER TABLE "encargo_materiales" ADD FOREIGN KEY ("encargo_id") REFERENCES "encargos" ("id") ON DELETE CASCADE;
ALTER TABLE "encargo_materiales" ADD FOREIGN KEY ("material_id") REFERENCES "materia_materiales" ("id") ON DELETE CASCADE;

-- Evaluaciones y Asistencia
ALTER TABLE "calificaciones" ADD FOREIGN KEY ("encargo_id") REFERENCES "encargos" ("id") ON DELETE RESTRICT;
ALTER TABLE "calificaciones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "asistencia" ADD FOREIGN KEY ("asignacion_id") REFERENCES "asignaciones_docentes" ("id") ON DELETE RESTRICT;

-- Módulo Financiero
ALTER TABLE "planes_pago" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE CASCADE;
ALTER TABLE "cuotas_plan_pago" ADD FOREIGN KEY ("plan_id") REFERENCES "planes_pago" ("id") ON DELETE CASCADE;
ALTER TABLE "pensiones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "pensiones" ADD FOREIGN KEY ("periodo_id") REFERENCES "periodos_academicos" ("id") ON DELETE RESTRICT;
ALTER TABLE "pensiones" ADD FOREIGN KEY ("plan_pago_id") REFERENCES "planes_pago" ("id") ON DELETE SET NULL;

ALTER TABLE "pagos" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id") ON DELETE RESTRICT;
ALTER TABLE "pagos" ADD FOREIGN KEY ("registrado_por") REFERENCES "usuarios" ("id") ON DELETE RESTRICT;

ALTER TABLE "pago_pensiones" ADD FOREIGN KEY ("pago_id") REFERENCES "pagos" ("id") ON DELETE CASCADE;
ALTER TABLE "pago_pensiones" ADD FOREIGN KEY ("pension_id") REFERENCES "pensiones" ("id") ON DELETE RESTRICT;