import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Image, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../../context/AuthContext';
import { useUsuarioDetail, useUsuarioUpdate } from '../../hooks/useUsuarios';
import { BentoCard } from '../components/BentoCard';
import { getFullName } from '../../utils/validation';
import type { Genero, UsuarioCont } from '../../types';

const GENEROS: Genero[] = ['masculino', 'femenino', 'otro'];

export function ProfileScreen() {
  const { user, updateLocalUser, logout } = useAuth();
  const { usuario, loading: loadingDetail, fetchById } = useUsuarioDetail();
  const { loading: saving, update, updateWithPhoto } = useUsuarioUpdate();
  const [form, setForm] = useState({ nombre: '', apellidoPaterno: '', apellidoMaterno: '', nacimiento: '', genero: 'otro' as Genero, username: '', email: '', celular: '', whatsapp: '', zona: '', distrito: '', calle: '', referencia: '', password: '' });
  const [fotoUri, setFotoUri] = useState<string | null>(null);
  const set = (key: keyof typeof form) => (value: string) => setForm((old) => ({ ...old, [key]: value } as typeof form));

  useEffect(() => { if (user?.id) void fetchById(user.id); }, [user?.id, fetchById]);
  useEffect(() => {
    if (!usuario) return;
    const contact = (type: UsuarioCont['tipo']) => usuario.contactos?.find((c) => c.tipo === type)?.contenido ?? '';
    setForm({ nombre: usuario.nombre ?? '', apellidoPaterno: usuario.apellidoPaterno ?? '', apellidoMaterno: usuario.apellidoMaterno ?? '', nacimiento: usuario.nacimiento?.slice(0, 10) ?? '', genero: (usuario.genero as Genero) ?? 'otro', username: usuario.cuenta?.username ?? usuario.username ?? '', email: usuario.cuenta?.email ?? usuario.email ?? '', celular: contact('Celular'), whatsapp: contact('Whatsapp'), zona: usuario.direccion?.zona ?? '', distrito: usuario.direccion?.distrito ?? '', calle: usuario.direccion?.calle ?? '', referencia: usuario.direccion?.referencia ?? '', password: '' });
  }, [usuario]);

  const missing = useMemo(() => [!form.nombre && 'nombre', !form.apellidoPaterno && 'apellido paterno', !form.apellidoMaterno && 'apellido materno', !form.nacimiento && 'fecha de nacimiento', !form.email && 'correo', !form.celular && 'celular', !form.zona && 'dirección', !(usuario?.documentos?.length) && 'documento de identidad'].filter(Boolean) as string[], [form, usuario?.documentos]);
  const pickImage = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.8 }); if (!result.canceled) setFotoUri(result.assets[0].uri); };
  const handleSave = async () => {
    if (!user?.id) return;
    const contactos = [{ tipo: 'Celular' as const, contenido: form.celular }, { tipo: 'Whatsapp' as const, contenido: form.whatsapp }].filter((c) => c.contenido);
    const payload = { nombre: form.nombre, apellidoPaterno: form.apellidoPaterno, apellidoMaterno: form.apellidoMaterno, nacimiento: form.nacimiento, genero: form.genero, cuenta: { username: form.username, email: form.email, ...(form.password ? { password: form.password } : {}) }, contactos, direccion: form.zona ? { zona: form.zona, distrito: form.distrito || null, calle: form.calle || null, referencia: form.referencia || null } : undefined };
    try { const result = fotoUri ? await updateWithPhoto(user.id, payload, fotoUri) : await update(user.id, payload); updateLocalUser({ nombre: form.nombre, apellidoPaterno: form.apellidoPaterno, apellidoMaterno: form.apellidoMaterno, username: form.username, email: form.email, fotoUrl: result.fotoUrl ?? user.fotoUrl }); setFotoUri(null); set('password')(''); Alert.alert('Perfil actualizado', 'Tus datos se guardaron correctamente.'); void fetchById(user.id); } catch { Alert.alert('No se pudo actualizar', 'Verifica los datos e inténtalo nuevamente.'); }
  };
  if (loadingDetail && !usuario) return <View className="flex-1 items-center justify-center py-20"><ActivityIndicator size="large" color="#801529" /></View>;
  const photo = fotoUri ?? usuario?.fotoUrl ?? user?.fotoUrl;
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerClassName="gap-4">
    <View className="gap-4 md:flex-row"><BentoCard className="p-6 md:flex-1 bg-maroon"><View className="items-center"><TouchableOpacity onPress={pickImage} className="relative">{photo ? <Image source={{ uri: photo }} className="w-28 h-28 rounded-full border-4 border-white/30" /> : <View className="w-28 h-28 rounded-full bg-white/15 items-center justify-center"><Text className="text-white text-4xl font-bold">{form.nombre.charAt(0) || 'U'}</Text></View>}<View className="absolute bottom-0 right-0 w-9 h-9 bg-white rounded-full items-center justify-center"><Ionicons name="camera" size={17} color="#801529" /></View></TouchableOpacity><Text className="text-white text-xl font-bold mt-4 text-center">{getFullName(form.nombre, form.apellidoPaterno, form.apellidoMaterno)}</Text><Text className="text-white/70 text-sm mt-1">@{form.username || user?.username}</Text><Text className="text-white/60 text-xs mt-3 uppercase">{usuario?.rol ?? 'Usuario'} · ID {user?.id}</Text></View></BentoCard><BentoCard className="p-5 md:flex-[2]"><View className="flex-row items-center gap-3"><View className={`w-10 h-10 rounded-xl items-center justify-center ${missing.length ? 'bg-amber-100' : 'bg-green-100'}`}><Ionicons name={missing.length ? 'alert-circle' : 'checkmark-circle'} size={23} color={missing.length ? '#B45309' : '#16A34A'} /></View><View className="flex-1"><Text className="text-base font-bold text-gray-900">{missing.length ? 'Completa tu información' : 'Información completa'}</Text><Text className="text-sm text-gray-500">{missing.length ? `Faltan: ${missing.join(', ')}.` : 'Tu perfil está listo y actualizado.'}</Text></View></View></BentoCard></View>
    <BentoCard className="p-5"><Title icon="person-outline" title="Datos personales" subtitle="Información básica de tu perfil" /><View className="gap-4 md:flex-row md:flex-wrap"><Field label="Nombre" value={form.nombre} onChangeText={set('nombre')} container="md:w-[31%]" /><Field label="Apellido paterno" value={form.apellidoPaterno} onChangeText={set('apellidoPaterno')} container="md:w-[31%]" /><Field label="Apellido materno" value={form.apellidoMaterno} onChangeText={set('apellidoMaterno')} container="md:w-[31%]" /><Field label="Nacimiento (AAAA-MM-DD)" value={form.nacimiento} onChangeText={set('nacimiento')} placeholder="2000-01-31" container="md:w-[31%]" /><View className="md:w-[31%]"><Text className="text-xs font-semibold text-gray-500 uppercase mb-1.5">Género</Text><View className="flex-row gap-2">{GENEROS.map((item) => <TouchableOpacity key={item} onPress={() => setForm((old) => ({ ...old, genero: item }))} className={`flex-1 rounded-xl py-3 items-center ${form.genero === item ? 'bg-maroon' : 'bg-gray-100'}`}><Text className={`text-xs font-semibold capitalize ${form.genero === item ? 'text-white' : 'text-gray-600'}`}>{item}</Text></TouchableOpacity>)}</View></View></View></BentoCard>
    <View className="gap-4 md:flex-row"><BentoCard className="p-5 md:flex-1"><Title icon="mail-outline" title="Acceso y contacto" /><View className="gap-4"><Field label="Usuario" value={form.username} onChangeText={set('username')} /><Field label="Correo electrónico" value={form.email} onChangeText={set('email')} keyboardType="email-address" /><Field label="Celular" value={form.celular} onChangeText={set('celular')} keyboardType="phone-pad" /><Field label="WhatsApp" value={form.whatsapp} onChangeText={set('whatsapp')} keyboardType="phone-pad" /><Field label="Nueva contraseña (opcional)" value={form.password} onChangeText={set('password')} secureTextEntry placeholder="Mínimo 8 caracteres" /></View></BentoCard><BentoCard className="p-5 md:flex-1"><Title icon="location-outline" title="Dirección" /><View className="gap-4"><Field label="Zona" value={form.zona} onChangeText={set('zona')} /><Field label="Distrito" value={form.distrito} onChangeText={set('distrito')} /><Field label="Calle" value={form.calle} onChangeText={set('calle')} /><Field label="Referencia" value={form.referencia} onChangeText={set('referencia')} /></View></BentoCard></View>
    <BentoCard className="p-5"><Title icon="document-text-outline" title="Documentos registrados" />{usuario?.documentos?.length ? usuario.documentos.map((doc) => <View key={doc.id ?? doc.numeroDoc} className="flex-row items-center gap-3 bg-gray-50 rounded-xl p-3 mb-2"><Ionicons name="card-outline" size={21} color="#801529" /><View><Text className="font-semibold text-gray-800">{doc.tipoDoc}</Text><Text className="text-sm text-gray-500">{doc.numeroDoc}</Text></View></View>) : <Text className="text-amber-700 bg-amber-50 p-3 rounded-xl">Aún no tienes documentos registrados. Completa esta información con administración.</Text>}</BentoCard>
    {usuario?.apoderados?.length ? <BentoCard className="p-5"><Title icon="people-outline" title="Apoderados registrados" />{usuario.apoderados.map((apoderado) => <View key={apoderado.apoderadoId} className="flex-row items-center gap-3 bg-gray-50 rounded-xl p-3 mb-2"><Ionicons name="person-outline" size={21} color="#801529" /><View><Text className="font-semibold text-gray-800">{getFullName(apoderado.nombre, apoderado.apellidoPaterno, apoderado.apellidoMaterno)}</Text><Text className="text-sm text-gray-500">{apoderado.parentesco}{apoderado.esPrincipal ? ' · Principal' : ''}</Text></View></View>)}</BentoCard> : null}
    <TouchableOpacity onPress={handleSave} disabled={saving} className="bg-maroon rounded-2xl py-4 items-center">{saving ? <ActivityIndicator color="#fff" /> : <Text className="text-white font-bold">Guardar cambios</Text>}</TouchableOpacity><TouchableOpacity onPress={logout} className="border border-red-200 rounded-2xl py-3 flex-row items-center justify-center gap-2"><Ionicons name="log-out-outline" size={18} color="#DC2626" /><Text className="text-red-600 font-semibold">Cerrar sesión</Text></TouchableOpacity>
  </ScrollView>;
}
function Title({ icon, title, subtitle }: { icon: keyof typeof Ionicons.glyphMap; title: string; subtitle?: string }) { return <View className="flex-row items-center gap-2 mb-4"><Ionicons name={icon} size={21} color="#801529" /><View><Text className="text-lg font-bold text-gray-900">{title}</Text>{subtitle ? <Text className="text-xs text-gray-400">{subtitle}</Text> : null}</View></View>; }
function Field({ label, value, onChangeText, keyboardType = 'default', secureTextEntry, placeholder, container = '' }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'default' | 'email-address' | 'phone-pad'; secureTextEntry?: boolean; placeholder?: string; container?: string }) { return <View className={container}><Text className="text-xs font-semibold text-gray-500 uppercase mb-1.5">{label}</Text><TextInput className="bg-gray-50 rounded-xl px-4 py-3 text-gray-800 border border-gray-200" value={value} onChangeText={onChangeText} keyboardType={keyboardType} secureTextEntry={secureTextEntry} placeholder={placeholder} placeholderTextColor="#9CA3AF" /></View>; }
