-- Materias y temas por GRADO (nivel + grado), no por paralelo.
--
-- 1°A y 1°B comparten las mismas materias y los mismos temas, así que la
-- configuración vive a nivel de grado. Los paralelos siguen existiendo como
-- filas de `cursos` porque horarios, inscripciones y asignaciones docentes sí
-- son por paralelo; lo que se une es la materia y el temario.
--
-- `curso_materias` queda reemplazado por `grado_materias`; la malla curricular
-- de la gestión se arma desde acá.
--
-- Ejecutar sobre bases con BDmain.sql y/o las migraciones anteriores.

BEGIN;

-- ── Materias por grado ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "grado_materias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel" VARCHAR(30) NOT NULL
    CHECK ("nivel" IN ('inicial', 'primaria', 'secundaria', 'bachillerato')),
  "grado" VARCHAR(20) NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "tipo_materia" VARCHAR(20) NOT NULL DEFAULT 'principal'
    CHECK ("tipo_materia" IN ('principal', 'extracurricular')),
  "carga_horaria_semanal" SMALLINT NOT NULL DEFAULT 5
    CHECK ("carga_horaria_semanal" > 0),
  "orden" SMALLINT NOT NULL DEFAULT 0,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_grado_materia" UNIQUE ("nivel", "grado", "materia_id")
);

CREATE INDEX IF NOT EXISTS "idx_grado_materias_grado"
  ON "grado_materias" ("nivel", "grado");
CREATE INDEX IF NOT EXISTS "idx_grado_materias_materia"
  ON "grado_materias" ("materia_id");

-- ── Temas de la maya curricular, por grado y materia ────────────────────────
-- El temario es reutilizable: se define una vez y lo usan todas las gestión.
CREATE TABLE IF NOT EXISTS "malla_temas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel" VARCHAR(30) NOT NULL
    CHECK ("nivel" IN ('inicial', 'primaria', 'secundaria', 'bachillerato')),
  "grado" VARCHAR(20) NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "unidad" SMALLINT NOT NULL DEFAULT 1 CHECK ("unidad" > 0),
  "titulo" VARCHAR(200) NOT NULL,
  "contenidos" TEXT,
  "horas_previstas" SMALLINT NOT NULL DEFAULT 1 CHECK ("horas_previstas" > 0),
  "es_evaluacion" BOOLEAN NOT NULL DEFAULT false,
  "orden" SMALLINT NOT NULL DEFAULT 0,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_malla_tema" UNIQUE ("nivel", "grado", "materia_id", "unidad")
);

CREATE INDEX IF NOT EXISTS "idx_malla_temas_grado_materia"
  ON "malla_temas" ("nivel", "grado", "materia_id");

-- ── Migrar lo ya configurado en curso_materias ─────────────────────────────
-- Se agrupa por nivel+grado: si 1°A y 1°B tenían la misma materia, se
-- colapsa en una sola fila.
INSERT INTO "grado_materias" ("nivel", "grado", "materia_id", "tipo_materia", "carga_horaria_semanal", "orden")
SELECT DISTINCT ON (c.nivel, c.grado, cm.materia_id)
       c.nivel, c.grado, cm.materia_id, cm.tipo_materia,
       cm.carga_horaria_semanal, MIN(cm.orden)
FROM curso_materias cm
JOIN cursos c ON c.id = cm.curso_id
GROUP BY c.nivel, c.grado, cm.materia_id, cm.tipo_materia, cm.carga_horaria_semanal
ORDER BY c.nivel, c.grado, cm.materia_id;

-- La tabla vieja ya no es la fuente de verdad: todo lo que tenía se acaba de
-- copiar arriba. Se elimina para que nadie vuelva a escribir por paralelo.
DROP TABLE IF EXISTS curso_materias;

COMMIT;
