-- Materias asignadas a cada curso base.
--
-- Flujo nuevo: se asignan las materias al CURSO BASE (cursos) una sola vez, y
-- al generar la estructura de una gestión escolar se cargan únicamente los
-- cursos que ya tengan al menos una materia. Así se evita configurar la malla
-- grado por grado y por cada paralelo de nuevo en cada gestión.
--
-- Ejecutar sobre bases creadas con BDmain.sql o con migraciones anteriores.

BEGIN;

CREATE TABLE IF NOT EXISTS "curso_materias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_id" BIGINT NOT NULL,
  "materia_id" BIGINT NOT NULL,
  "tipo_materia" VARCHAR(20) NOT NULL DEFAULT 'principal'
    CHECK ("tipo_materia" IN ('principal', 'extracurricular')),
  "carga_horaria_semanal" SMALLINT NOT NULL DEFAULT 5
    CHECK ("carga_horaria_semanal" > 0),
  "orden" SMALLINT NOT NULL DEFAULT 0,
  "fecha_creacion" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_curso_materia" UNIQUE ("curso_id", "materia_id")
);

CREATE INDEX IF NOT EXISTS "idx_curso_materias_curso" ON "curso_materias" ("curso_id");
CREATE INDEX IF NOT EXISTS "idx_curso_materias_materia" ON "curso_materias" ("materia_id");

COMMIT;
